spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: {cognito.client_id}
            client-secret: {cognito.client_secret}
            provider: cognito
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            client-name: {cognito.client_name}
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuerUri: https://cognito-idp.{aws.region}.amazonaws.com/{cognito.user_pool_id}
            user-name-attribute: cognito:username
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources: # Static resources
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

logging:
  level:
    org:
      springframework:
        security: DEBUG