spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: xxx
            client-secret: yyy
            provider: cognito
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            client-name: webapp
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-west-1.amazonaws.com/{pool}
            authorization-uri: https://{domain}.auth.eu-west-1.amazoncognito.com/oauth2/authorize
            token-uri: https://{domain}.auth.eu-west-1.amazoncognito.com/oauth2/token
            user-info-uri: https://{domain}.auth.eu-west-1.amazoncognito.com/oauth2/userInfo
            user-name-attribute: cognito:username
            jwk-set-uri: https://cognito-idp.ap-northeast-1.amazonaws.com/{pool}/.well-known/jwks.json
logging:
  level:
    org:
      springframework:
        security: DEBUG